#!/bin/sh

dn="$(ldapwhoami -Q 2>/dev/null)" || { echo >&2 'Unable to obtain user DN'; exit 1; }
dn="${dn#dn:}"
tmp="$(mktemp)" || { echo >&2 'Cannot open a temporary file' && exit 2; }

ldapsearch -LLL -o ldif-wrap=no -l 3 -Q -b "$dn" -s base '(objectClass=*)' authorizedKeys | sed '/^authorizedKeys: /!d;s///' > "$tmp"
"${EDITOR:-vi}" "$tmp" || { echo >&2 'Editor exited non-zero'; rm "$tmp"; exit 4; }
awk 'BEGIN { print "dn: '"$dn"'\nchangeType: modify\nreplace: authorizedKeys" }; /^ssh-/{ print "authorizedKeys: " $0 }' "$tmp" | ldapmodify -Q || { echo >&2 'Could not update authroized keys'; rm "$tmp"; exit 3; }
rm "$tmp"
