#!/bin/bash
dn="$(ldapwhoami -Q 2>/dev/null)" || { echo >&2 'Unable to obtain user DN'; exit 1; }
dn="${dn#dn:}"
i=0
for session in /usr/share/xsessions/*; do
	filename="${session##*/}"
	options[i++]="${filename%.*}"
	options[i++]="$(grep -Po '(?<=^Name=).*' "$session")"
done
height="$((i/2+10))"
width=70
choice_height="$((i/2))"
choice="$(dialog --clear \
		--backtitle 'Collegium V' \
		--title 'Change Desktop Environment' \
		--menu 'Choose a Desktop Environment' \
		$height $width $choice_height \
		"${options[@]}" \
		2>&1 >/dev/tty)"
clear
[ -z "$choice" ] && exit 0
printf "dn: %s\nchangetype: modify\nreplace: desktopEnvironment\ndesktopEnvironment: %s\n-\n" "$dn" "$choice" | ldapmodify -Q || { echo >&2 'Could not update desktop environment'; exit 3; }
