---
- name: Install NUT
  xbps: pkg=network-ups-tools state=present

- name: Configure UPS Drivers
  template: src=ups.conf dest=/etc/ups/ups.conf owner=root group=nut mode=0640
  notify:
    - upsdrvctl

- name: Configure NUT
  copy: src=nut.conf dest=/etc/ups/nut.conf owner=root group=nut mode=0640
  notify:
    - upsd

- name: Set nut network passwords
  template: src=upsd.users dest=/etc/ups/upsd.users owner=root group=nut mode=0640
  notify:
    - upsd

- name: Configure UPSD
  copy: src=upsd.conf dest=/etc/ups/upsd.conf owner=root group=nut mode=0644
  notify:
    - upsd

- name: Install firewall rules
  copy: src=upsd.rules dest=/etc/iptables.d/upsd.rules owner=root group=root mode=0640
  notify:
    - iptables

- name: Enable NUT services
  file: src=/etc/sv/{{ item }} dest=/var/service/{{ item }} state=link owner=root group=root
  with_items:
    - upsd
    - upsdrvctl
