---
- hosts: audio
  become: yes
  become_method: sudo
  roles:
    - network
    - xbps-repoconf
    - core-daemons
    - core-programs
    - sshd
    - audio
    - netlogon
    - nut-server
    - upsmon
    - netdata
