#!/bin/sh

ldapsearch -LLL -o ldif-wrap=no -l 3 -H 'ldap://ldap.collegiumv.org' -x -b "uid=$1,ou=People,dc=collegiumv,dc=org" -s base '(objectClass=*)' authorizedKeys | sed '/^authorizedKeys: /!d;s///'
