#!/usr/bin/env bash

dn="$(ldapsearch -LLL -o ldif-wrap=no -H 'ldaps://beryllium.ad.collegiumv.org' -x -D "$(whoami)@ad.collegiumv.org" -W -b 'DC=ad,DC=collegiumv,DC=org' '(sAMAccountName='"$(whoami)"')' dn | grep '^dn:')"
echo "$dn
delete: gecos" | ldapmodify -H 'ldaps://beryllium.ad.collegiumv.org' -x -D "$(whoami)@ad.collegiumv.org" -W
