# /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin

if [[ ! "$(/usr/local/sbin/ssh_pubkeys "$(whoami)")" =~ '^ssh-' ]]; then
	tput setaf 2 && echo "
Add your pubkey with  add_pubkey <file_containing_pubkey>
It will also make this notice go away!" && tput sgr0
fi
