#!/bin/bash


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PATH=$PATH:$DIR

export INVENTORY_FILE=$DIR/../inventory

alias cvReboot="cvReboot | ansible_table"
alias cvWake="cvWake | ansible_table"
alias cvWho="cvWho | ansible_table"
